Local Spare Time Gizmos Changes

diff --git a/src/makefile b/src/makefile
--- a/src/makefile
+++ b/src/makefile
@@ -1,9 +1,19 @@
-CFLAGS ?= -O -g
+#####
+#
+# Makefile for macro11 and dumpobj
+#
+
+WARNS     ?= -Wall -Wshadow -Wextra -pedantic -Woverflow -Wstrict-overflow
+OBJFORMAT ?= -DDEFAULT_OBJECTFORMAT_RT11=0
+SANITIZE  ?= #-fsanitize=address -fsanitize=undefined -fsanitize-recover=all -fno-omit-frame-pointer
+DEBUG     ?= -ggdb $(SANITIZE)
+OPT       ?= -O3
+CFLAGS    ?= -std=gnu99 $(WARNS) $(DEBUG) $(OPT) $(OBJFORMAT)
 
 MACRO11_SRCS = macro11.c \
 	assemble.c assemble_globals.c assemble_aux.c	\
 	extree.c listing.c macros.c parse.c rept_irpc.c symbols.c \
-	mlb.c object.c stream2.c util.c rad50.c
+	mlb2.c mlb-rsx.c mlb-rt11.c object.c stream2.c util.c rad50.c
 
 MACRO11_OBJS = $(MACRO11_SRCS:.c=.o)
 
@@ -18,27 +28,28 @@ all: macro11 dumpobj
 tags: macro11 dumpobj
 	ctags *.c *.h
 
-macro11: $(MACRO11_OBJS) makefile
+macro11: git-info.h $(MACRO11_OBJS) Makefile
 	$(CC) $(CFLAGS) -o macro11 $(MACRO11_OBJS) -lm
 
-dumpobj: $(DUMPOBJ_OBJS) makefile
+dumpobj: $(DUMPOBJ_OBJS) Makefile
 	$(CC) $(CFLAGS) -o dumpobj $(DUMPOBJ_OBJS)
 
-MACRO11_OBJS: makefile
-DUMPOBJ_OBJS: makefile
+$(MACRO11_OBJS): Makefile
+$(DUMPOBJ_OBJS): Makefile
+
+git-info.h:
+	#./make-git-info
+	@echo "" >git-info.h
+
+# Bootstrap dependency on the git header file, which otherwise
+# gets generated too late.
+macro11.o: git-info.h
+macro11.c: git-info.h
 
 clean:
 	-rm -f $(MACRO11_OBJS) $(DUMPOBJ_OBJS) macro11 dumpobj
-
-macro11.o: macro11.c macro11.h rad50.h object.h  stream2.h \
- mlb.h util.h
-mlb.o: mlb.c  rad50.h stream2.h mlb.h macro11.h util.h
-object.o: object.c rad50.h object.h
-stream2.o: stream2.c macro11.h  stream2.h
-util.o: util.c util.h
-rad50.o: rad50.c rad50.h
-dumpobj.o: dumpobj.c rad50.h util.h
-rad50.o: rad50.c rad50.h
+	-rm -f *.d
+	-rm -f git-info.h
 
 # Since the only tests we have so far are for crashes,
 # just try to assemble. Later, we will need expected/actual tests.
@@ -47,17 +58,31 @@ rad50.o: rad50.c rad50.h
 argtests: macro11
 	@ for OPT in -e -d -m -p -o -l -ysl ; do \
 	  ./macro11 foo.mac $$OPT     2> /dev/null; \
-    if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
-    echo "  $$OPT missing value"; \
+	  if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
+	  echo "  $$OPT missing value"; \
 	  ./macro11 foo.mac $$OPT -v  2> /dev/null; \
-    if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
-    echo "  $$OPT fol. by option"; \
-	done
+	  if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
+	  echo "  $$OPT fol. by option"; \
+	  done
 	@ ./macro11 foo.mac $$OPT -x -v 2> /dev/null; \
-    if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
-    echo "  -x must be the last option"
+	  if (( $$? == 1 )); then echo PASS; else echo FAIL; fi; \
+	   echo "  -x must be the last option"
 
 tests: macro11 argtests
 	@ ACTUAL=`./macro11 tests/test-undef.mac 2>&1`; \
 	if [ "tests/test-undef.mac:1: ***ERROR MACRO .TTYOU not found" == "$$ACTUAL" ]; then echo PASS; else echo FAIL; fi; \
 	echo "  test-undef.mac"
+
+# Automatic dependency generation
+
+ifneq ($(MAKECMDGOALS),clean)
+-include $(ALL_SRCS:.c=.d)
+endif
+
+# Make .d files as side effect of compiling .c to .o
+%.d %.o: %.c
+	$(CC) $(CFLAGS) -c -o $*.o $<
+	@set -e; rm -f $*.d; \
+	    $(CC) -MM $(CPPFLAGS) $< > $@.$$$$; \
+	    sed 's,\($*\)\.o[ :]*,\1.o \1.d : ,g' < $@.$$$$ > $*.d; \
+	    rm -f $@.$$$$
